<Project>
  <PropertyGroup>
    <Company>USD.Net</Company>
    <Product>USD.Net</Product>
    <Copyright>Copyright © 2025</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <WarningsNotAsErrors>NU1605</WarningsNotAsErrors>
  </PropertyGroup>
</Project>