<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>USD.Net</PackageId>
    <PackageVersion>0.1.0-alpha</PackageVersion>
    <Authors>Geoff Gerber</Authors>
    <Description>.NET library for working with Pixar's Universal Scene Description (USD) format</Description>
    <PackageTags>USD;Pixar;3D;Animation;Graphics;SceneGraph</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/markemp/USD.Net</RepositoryUrl>
    <PackageProjectUrl>https://github.com/markemp/USD.Net</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>